# Aliases
alias ll='ls -alF'
alias ls='ls --color=auto'
alias home='cd ~'
alias python='python3'

alias github='cd ~/Documents/GitHub/'
alias base='conda activate base'
alias mri='conda activate siamese'
alias debase='conda deactivate'
alias twitdl='python3 twitter_downloader.py'

alias smi='echo 'nvidia-smi' | frodo'
alias gpustat='echo 'gpustat' | frodo'

alias nii2mesh='/Users/arnaud/Documents/GitHub/nii2mesh/src/nii2mesh'
alias niimath='/Users/arnaud/Documents/GitHub/niimath/build/bin/niimath'

# frodo
alias frodo='ssh arnaud@frodo.toelt.ai'
alias 192='ssh arnaud@192.168.1.33'
alias xavier='ssh -J arnaud@frodo.toelt.ai nvidia@xavier'
alias mathias='ssh ubuntu@217.182.199.223'

# localhost + arg
alias localhost='f(){ echo Opened chrome at localhost:"$1" ; /usr/bin/open -a /Applications/Google\ Chrome.app http://localhost:$1 ; unset -f f; }; f'


# starship
# eval "$(starship init zsh)"
# plugins=(virtualenv)
# warp
export CLICOLOR=1


# freesurfer
# export FS_ALLOW_DEEP=1
# export FREESURFER_HOME=/Applications/freesurfer
# export SUBJECTS_DIR=$FREESURFER_HOME/subjects
# source $FREESURFER_HOME/SetUpFreeSurfer.sh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/arnaud/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/arnaud/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/arnaud/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/arnaud/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

#starship
eval "$(starship init zsh)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/arnaud/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/arnaud/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/arnaud/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/arnaud/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
# export PATH=/Applications/freesurfer/python:/Users/arnaud/Downloads/google-cloud-sdk/bin:/Users/arnaud/miniconda3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/TeX/texbin

